### ISSUE TITLE
differential expression analysis

### ISSUE THREAD

**Issue by abedkurdi** [bioinfo-biols/CIRI-cookbook#26]
Hello there,
Thanks a lot for this package! I just have a question about the differential expression analysis, just to make sure I am reading the output in the correct way: when we say differential expression here, the results shown are for **case vs control** and not for **control vs case**, right?

Thanks in advance.

**Comment by Kevinzjy** [comment]
Hi @abedkurdi , 

Yes, you are correct. The positive values in the DE output mean that genes are up-regulated in the case samples compared to the control samples.

**Comment by abedkurdi** [comment]
Thank you for the answer! Just to more questions:
- Are those log2 fold change values?
- Are we supposed to use both DE and DS scores together?

Thanks again.

**Comment by Kevinzjy** [comment]
Are you using the single-vs-single mode of CIRIquant? The DE score and DS score measure the extent of changes but are not directly calculated like log2fc. The DE and DS scores represent the change in expression level and junction ratio respectively.

**Comment by abedkurdi** [comment]
basically I am going to use the biological replicates mode and not the single-vs-single mode.

**Comment by Kevinzjy** [comment]
Then the log2FC will be presented in the output file, the DE column only tells you which gene is significantly upregulated (1) or downregulated (1).

**Comment by abedkurdi** [comment]
Thanks a lot for your answers!
