### ISSUE TITLE
CIRIquant

### ISSUE THREAD

**Issue by ashleyhappiness** [bioinfo-biols/CIRI-cookbook#30]
Hi all,
When I run CIRIquant, I am able to run CIRIquant to completion but have not been able to get out anything in the gene folder. The .log says "Error: no valid ID found for GFF record" which is weird since the manual doesn't ask for a GFF file. When I use a GFF file instead of a GTF file, I am able to get a gene abundance score but the program will no longer run to completion. I need the gene abundance scores for DE (with biological replicates). Is there something that I might be doing wrong to get this error?
A

**Comment by Kevinzjy** [comment]
Hi @ashleyhappiness,

What's the source of your GTF file? We recommend running CIRIquant with the GENCODE gtf. I've also tested the Ensembl gtf and CIRIquant works fine.

**Comment by ashleyhappiness** [comment]
Updating... When I run CIRIquant with an Ensembl gtf, then I can get the whole thing to work without an issue
