### ISSUE TITLE
CIRI-AS command issues Please make sure the SAM is the same one used for circRNA detection by CIRI without modification! eventhough I am using the same SAM file

### ISSUE THREAD

**Issue by iichelhadi** [bioinfo-biols/CIRI-cookbook#6]
trying to run CIRI-AS after running both CIRIv1 and CIRI2 and I am encountering different issues for both.
When running CIRIv1 I get the following error:
Please make sure all the reads have the same read lengths!
When running CIRI2 I get error that everyone else gets:
"Please make sure the SAM is the same one used for circRNA detection by CIRI without modification!"

I used the same SAM file for all. I was also wondering if it is a good idea to use raw fastq files (NO adapter trimming) with CIRI. Does that affect the results?

**Comment by Kevinzjy** [comment]
Hi @iichelhadi , CIRI-AS  needs untrimmed reads input. Could you try running CIRI2 & CIRI-AS with raw fastq instead?

**Comment by iichelhadi** [comment]
> Hi @iichelhadi , CIRI-AS needs untrimmed reads input. Could you try running CIRI2 & CIRI-AS with raw fastq instead?

just did, It worked. thank you
